config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper
  devise_for(
    :users,
    path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { invitations: 'users/invitations' }
  )
  resources :campaigns
  resources :members
  resources :wallets
  resources :users
  root 'campaigns#index'

  namespace :api do
    namespace :v1 do
      scope ':store_id' do
        resources :transactions, only: %i[create]
      end
    end
  end
end

app/models/wallet.rb
# frozen_string_literal: true

class Wallet < ApplicationRecord
  # Didin't use enum as dont needed it's functationlity
  EXPIRE_METHODS = {
    'After X days' => 'after_x_days',
    is_all_time_active: 'is_all_time_active',
    at_the_end_of_the_month: 'at_the_end_of_the_month',
    at_the_end_of_the_xth_year: 'at_the_end_of_the_xth_year',
    units_will_expire_after: 'units_will_expire_after'
  }.freeze

  belongs_to :store
  has_many :transactions, dependent: :destroy

  validates :name, :active, :singular, :plural, :expire_unit_method, presence: true
  validates :expire_unit_method, inclusion: { in: EXPIRE_METHODS.values }
end

app/controllers/wallets_controller.rb
# frozen_string_literal: true

class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[show edit update destroy]

  # GET /wallets or /wallets.json
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1 or /wallets/1.json
  def show; end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit; end

  # POST /wallets or /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to wallet_url(@wallet), notice: t('notice.wallet.created') }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to wallet_url(@wallet), notice: t('notice.wallet.updated') }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy
    @wallet.destroy

    respond_to do |format|
      format.html { redirect_to wallets_url, notice: t('notice.wallet.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wallet
    @wallet = Wallet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def wallet_params
    params.require(:wallet).permit(:store_id, :name, :description, :active, :singular, :plural, :expire_unit_method)
  end
end

app/views/wallets/_form.html.erb
<%= simple_form_for(@wallet) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :active %>
  <%= f.input :singular %>
  <%= f.input :plural %>
  <%= f.input :expire_unit_method %>
  <div class="inline">
    <%= f.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/wallets/_wallet.html.erb
<div id="<%= dom_id wallet %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Store:</strong>
    <%= wallet.store_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= wallet.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= wallet.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Active:</strong>
    <%= wallet.active %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Singular:</strong>
    <%= wallet.singular %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Plural:</strong>
    <%= wallet.plural %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Expire unit method:</strong>
    <%= wallet.expire_unit_method %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this wallet", wallet, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this wallet', edit_wallet_path(wallet), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/wallets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing wallet</h1>

  <%= render "form", wallet: @wallet %>

  <%= link_to "Show this wallet", @wallet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to wallets", wallets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/wallets/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Wallets</h1>
    <%= link_to 'New wallet', new_wallet_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="wallets" class="min-w-full">
    <%= render @wallets %>
  </div>
</div>

app/views/wallets/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New wallet</h1>

  <%= render "form", wallet: @wallet %>

  <%= link_to 'Back to wallets', wallets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/wallets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @wallet %>

    <%= link_to 'Edit this wallet', edit_wallet_path(@wallet), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this wallet', wallet_path(@wallet), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to wallets', wallets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>