config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper
  devise_for(
    :users,
    path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { invitations: 'users/invitations' }
  )
  resources :campaigns
  resources :members
  resources :wallets
  resources :users
  root 'campaigns#index'

  namespace :api do
    namespace :v1 do
      scope ':store_id' do
        resources :transactions, only: %i[create]
      end
    end
  end
end

app/models/campaign.rb
# frozen_string_literal: true

class Campaign < ApplicationRecord
  belongs_to :store
  has_many :rules, dependent: :destroy

  accepts_nested_attributes_for :rules, allow_destroy: true

  enum :campaign_type, { direct: 0, referral: 1 }
  enum :trigger, { transaction_event: 0, internal_event: 1, custom_event: 2, achievement: 3, redemption: 4 }
end

app/controllers/campaigns_controller.rb
# frozen_string_literal: true

class CampaignsController < ApplicationController
  before_action :set_campaign, only: %i[show edit update destroy]

  # GET /campaigns or /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1 or /campaigns/1.json
  def show; end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit; end

  # POST /campaigns or /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaign_url(@campaign), notice: t('notice.campaign.created') }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1 or /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to campaign_url(@campaign), notice: t('notice.campaign.updated') }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1 or /campaigns/1.json
  def destroy
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: t('notice.campaign.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def campaign_params
    params
      .require(:campaign)
      .permit(
        :name,
        :description,
        :campaign_type,
        :trigger,
        :active,
        :active_from,
        :active_to,
        :order,
        :store_id,
        rules_attributes: [
          :store_id,
          :order,
          :_destroy,
          { conditions_attributes: %i[
            store_id
            order
            feature
            operators
            values
          ] }
        ]
      )
  end
end

app/views/campaigns/_campaign.html.erb
<tr id="<%= dom_id campaign %>">
  <td class="border border-slate-300 py-1 px-2"><%= campaign.order %></td>
  <td class="border border-slate-300 py-1 px-2"><%= campaign.name %></td>
  <td class="border border-slate-300 py-1 px-2"><%= campaign.campaign_type %></td>
  <td class="border border-slate-300 py-1 px-2"><%= campaign.active %></td>
  <td class="border border-slate-300 py-1 px-2"><%= campaign.active_from %></td>
  <td class="border border-slate-300 py-1 px-2"><%= campaign.active_to %></td>
  <td class="border border-slate-300 py-1 px-2"><%= campaign.created_at %></td>
  <td class="border border-slate-300 py-1 px-2">
    <%= link_to 'edit', edit_campaign_path(campaign) %>
  </td>
</tr>

app/views/campaigns/_condition_fields.html.erb
<div class="grid grid-cols-5 gap-4 items-center">
  <div>
  <%= f.input :order %>
  </div>
  <div>
  <%= f.input :feature %>
  </div>
  <div>
  <%= f.input :operators %>
  </div>
  <div>
  <%= f.input :values %>
  </div>
  <div>
  <%= link_to 'remove', 'javascript:void(0);', data: { action: 'campaigns#removeFields' } %>
  </div>
</fieldset>

app/views/campaigns/_form.html.erb
<%= simple_form_for(@campaign) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :campaign_type, as: :select, collection: Campaign.campaign_types.keys %>
  <%= f.input :trigger, as: :select, collection: Campaign.triggers.keys %>
  <%= f.input :active %>
  <%= f.input :active_from %>
  <%= f.input :active_to %>
  <%= f.input :order %>
  <h3>Rules</h3>
  <div class="p-5 bg-slate-100">
  <%= f.fields_for :rules do |builder| %>
    <% if builder.object %>
      <%= render 'rule_fields', f: builder %>
    <% end %>
  <% end %>
  </div>

  <%= link_to_add_fields 'Add Rule', f, :rules %>

  <div class="block mt-12">
    <%= f.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/campaigns/_rule_fields.html.erb
<div class="p-2 border rounded bg-white rule">
  <div class="flex">
    <h4 class="text-xl">Rule</h4>
    <div class="flex flex-1 justify-end">
      <%= f.hidden_field :_destroy %>
      <%= link_to 'remove', 'javascript:void(0);', data: { action: 'campaigns#removeFields' } %>
    </div>
  </div>
<h4>Conditions</h4>
<%= f.input :order %>
<%= f.fields_for :conditions do |builder| %>
  <%= render 'condition_fields', f: builder %>
<% end %>
<%= link_to_add_fields 'Add Condition', f, :conditions %>
</div>

app/views/campaigns/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing campaign</h1>

  <%= render "form", campaign: @campaign %>

  <%= link_to "Show this campaign", @campaign, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to campaigns", campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/campaigns/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="font-bold text-2xl">Campaigns</h1>
    <%= link_to 'Add Campaign', new_campaign_path, class: "rounded py-2 px-5 bg-indigo-600 text-white block font-small uppercase" %>
  </div>

  <table id="campaigns" class="border-collapse border border-slate-400 min-w-full">
    <thead>
      <tr class="bg-slate-100">
        <th class="border border-slate-300 py-1 px-1">Order</th>
        <th class="border border-slate-300 py-1 px-1">Name</th>
        <th class="border border-slate-300 py-1 px-1">Campaign type</th>
        <th class="border border-slate-300 py-1 px-1">Active</th>
        <th class="border border-slate-300 py-1 px-1">Active from</th>
        <th class="border border-slate-300 py-1 px-1">Active to</th>
        <th class="border border-slate-300 py-1 px-1">Created at</th>
        <th class="border border-slate-300 py-1 px-2"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @campaigns %>
    </tbody>
  </table>
</div>

app/views/campaigns/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New campaign</h1>

  <%= render "form", campaign: @campaign %>

  <%= link_to 'Back to campaigns', campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/campaigns/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @campaign %>

    <%= link_to 'Edit this campaign', edit_campaign_path(@campaign), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this campaign', campaign_path(@campaign), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to campaigns', campaigns_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>