config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper
  devise_for(
    :users,
    path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
    controllers: { invitations: 'users/invitations' }
  )
  resources :campaigns
  resources :members
  resources :wallets
  resources :users
  root 'campaigns#index'

  namespace :api do
    namespace :v1 do
      scope ':store_id' do
        resources :transactions, only: %i[create]
      end
    end
  end
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  belongs_to :store
  has_many :transactions, dependent: :destroy
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
  before_action :set_member, only: %i[show edit update destroy]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show; end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit; end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: t('notice.member.created') }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: t('notice.member.updated') }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url, notice: t('notice.member.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:name, :gender, :phone, :birth_date, :store_id)
  end
end

app/views/members/_form.html.erb
<%= form_with(model: member, class: "contents") do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :birth_date %>
    <%= form.date_field :birth_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/members/_member.html.erb
<tr id="<%= dom_id member %>" class="bg-white">
  <td class="border border-slate-300 py-1 px-1"><%= member.name %></td>
  <td class="border border-slate-300 py-1 px-1"><%= member.phone %></td>
  <td class="border border-slate-300 py-1 px-1"><%= member.created_at %></td>
  <td class="border border-slate-300 py-1 px-1">-</td>
  <td class="border border-slate-300 py-1 px-1">-</td>
  <td class="border border-slate-300 py-1 px-1">-</td>
  <td class="border border-slate-300 py-1 px-1">-</td>
  <td class="border border-slate-300 py-1 px-2"></td>
</tr>

app/views/members/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing member</h1>

  <%= render "form", member: @member %>

  <%= link_to "Show this member", @member, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to members", members_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/members/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-2xl">Members</h1>
    <%= link_to 'Add member', new_member_path, class: "btn btn-primary" %>
  </div>

  <table id="members" class="border-collapse border border-slate-400 min-w-full mt-8">
    <thead>
      <tr class="bg-white">
        <th class="border border-slate-300 py-1 px-1">Full name</th>
        <th class="border border-slate-300 py-1 px-1">Phone</th>
        <th class="border border-slate-300 py-1 px-1">Registration date</th>
        <th class="border border-slate-300 py-1 px-1">Transactions</th>
        <th class="border border-slate-300 py-1 px-1">Total earned Points</th>
        <th class="border border-slate-300 py-1 px-1">Active Points</th>
        <th class="border border-slate-300 py-1 px-1">Total spending</th>
        <th class="border border-slate-300 py-1 px-2"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @members %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New member</h1>

  <%= render "form", member: @member %>

  <%= link_to 'Back to members', members_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/members/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @member %>

    <%= link_to 'Edit this member', edit_member_path(@member), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this member', member_path(@member), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to members', members_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>